# Cấu hình cho hệ thống OCR
ocr:
  detector: "db_resnet50"       # Mô hình khoanh vùng chữ (Detection)
  #detector: "linknet_resnet50"
  recognizer: "crnn_vgg16_bn"      # Mô hình nhận diện chữ (Recognition)
  #recognizer: "parseq"
  pretrained: true              # Sử dụng trọng số đã huấn luyện sẵn
  device: "cpu"
  #device: "cuda" 